"""
Cross-validation and OOF (Out-of-Fold) instruction builders.
"""


def build_cv_instructions(working_dir: str, component_name: str) -> list[str]:
    """Build cross-validation instructions."""
    return [
        "\n🔄 CONSISTENT CROSS-VALIDATION (CRITICAL - USE CANONICAL FOLDS):",
        f"  - **MANDATORY**: Load canonical folds from `{working_dir}/canonical/folds.npy`",
        f"  - **MANDATORY**: Load canonical train_ids from `{working_dir}/canonical/train_ids.npy`",
        "  - **NEVER** create your own KFold/StratifiedKFold - canonical folds are already optimized",
        "    ```python",
        "    from pathlib import Path",
        "    import numpy as np",
        "",
        f"    canonical_dir = Path('{working_dir}') / 'canonical'",
        "    folds = np.load(canonical_dir / 'folds.npy')",
        "    train_ids = np.load(canonical_dir / 'train_ids.npy', allow_pickle=True)",
        "    with open(canonical_dir / 'metadata.json') as f:",
        "        canonical_metadata = json.load(f)",
        "    n_folds = int(canonical_metadata['n_folds'])",
        "",
        "    # `iter_canonical_cv_splits` is injected by the executor and is",
        "    # mandatory: for temporal CV, `folds != fold` leaks future rows.",
        "    for fold_idx, train_idx, val_idx in iter_canonical_cv_splits():",
        "        X_train, X_val = X[train_idx], X[val_idx]",
        "        y_train, y_val = y[train_idx], y[val_idx]",
        "        # ... train model on fold ...",
        "    ```",
        "  - NEVER replace `iter_canonical_cv_splits()` with `folds != fold`.",
        "  - Temporal folds use strict forward chaining and contain warm-up rows",
        "    marked fold=-1; those rows MUST remain NaN in OOF and MUST be",
        "    excluded only with `CANONICAL_OOF_ELIGIBLE_MASK` when scoring.",
        "  - WHY: Independent fold creation causes OOF misalignment → stacking ensemble fails",
        "  - CRITICAL: Fit FEATURE preprocessing/scalers INSIDE each CV fold (fit on X_train, transform X_val/X_test)",
        "  - EXCEPTION: TARGET LabelEncoder must be fit ONCE on FULL y BEFORE the CV loop (see tabular constraints)",
        f"  - CRITICAL: MUST save Out-of-Fold (OOF) predictions during CV to models/oof_{component_name}.npy",
        "  - OOF predictions enable proper stacking ensemble (meta-model trained on OOF)",
        "  - AFTER saving OOF/Test: print lines 'Saved OOF predictions to ...' and 'Saved test predictions to ...'",
        "  - Every candidate-produced .npy artifact must be pickle-free. Save "
        "text predictions, IDs, and class order as Unicode arrays (`dtype=str`), "
        "never `dtype=object`; the host rejects object/pickle arrays.",
        "  - MUST print 'Final Validation Performance: {score}'",
        "  - If the metric is NaN/inf, raise an error; never fabricate a replacement score",
        "  - Multiclass log_loss: after clipping, renormalize rows to sum to 1",
        "  - Initialize OOF with NaN; if any OOF-eligible canonical row remains unfilled after an early stop, checkpoint partial state and invalidate the candidate",
        "  - Treat class weighting/resampling as a candidate selected by the same validation protocol, not a mandatory default",
    ]


def build_stacking_oof_instructions(working_dir: str, component_name: str) -> list[str]:
    """Build stacking/OOF instructions."""
    instructions = [
        "\nSTACKING & OOF REQUIREMENTS (CRITICAL):",
        "  1. Initialize `oof_preds` with NaN (shape n_train x n_outputs) so an unfilled canonical row fails finite-value validation.",
        "  2. Initialize `test_preds` array of zeros with shape (n_test, n_classes) for multi-class.",
        "  2b. **SHAPE CHECKS (MUST)**:",
        "     - Set `n_train` and `n_test` from the actual model input entities.",
        "     - Use `len(sample_submission)` for `n_test` only when the submission is one row per test entity; long formats repeat each entity.",
        "     - Before saving: assert oof_preds.shape[0] == n_train and test_preds.shape[0] == n_test.",
        "     - If mismatch, raise ValueError (do NOT save corrupted arrays).",
        "  3. **CLASS ORDER ALIGNMENT (CRITICAL FOR ENSEMBLE - PREVENTS DEGRADATION)**:",
        "     - **STEP A**: Fit LabelEncoder on FULL y BEFORE the CV loop (NOT inside!):",
        "       ```python",
        "       from sklearn.preprocessing import LabelEncoder",
        "       le = LabelEncoder()",
        "       y_encoded = le.fit_transform(y)  # Fit on FULL training data",
        "       n_classes = len(le.classes_)",
        "       print(f'[LOG:INFO] Classes: {le.classes_} (n={n_classes})')",
        "       ```",
        "     - **STEP B**: Determine class order (HANDLE BOTH FORMATS!):",
        "       ```python",
        "       submission_cols = list(SUBMISSION_TARGET_COLS)",
        "       if not submission_cols:",
        "           raise ValueError('No declared submission target columns')",
        "       ",
        "       # CRITICAL: Detect submission format!",
        "       # Wide format (multi-column probabilities): ['1', '2', '3', '4', '5', '6', '7']",
        "       # Label format (single column): ['Cover_Type'] or ['target']",
        "       if len(submission_cols) > 1:",
        "           # Wide format - use column names as class order",
        "           class_order = submission_cols",
        "           print(f'[LOG:INFO] Wide format submission - class_order from columns: {class_order}')",
        "       else:",
        "           # Label format - use LabelEncoder classes as class order",
        "           class_order = le.classes_.tolist()",
        "           print(f'[LOG:INFO] Label format submission - class_order from LabelEncoder: {class_order}')",
        "       ```",
        "     - **STEP C**: Compute reordering indices (ONLY for wide format!):",
        "       ```python",
        "       le_classes = le.classes_.tolist()  # Model's LabelEncoder order",
        "       ",
        "       # For label format, no reordering needed (already aligned)",
        "       if len(submission_cols) > 1:",
        "           # Wide format: map LabelEncoder order to submission column order",
        "           reorder_idx = [le_classes.index(c) for c in class_order]",
        "       else:",
        "           # Label format: identity mapping (no reorder)",
        "           reorder_idx = list(range(len(le_classes)))",
        "       ```",
        "     - BEFORE saving, reorder predictions to match sample_submission:",
        "       ```python",
        "       oof_preds_aligned = oof_preds[:, reorder_idx]",
        "       test_preds_aligned = test_preds[:, reorder_idx]",
        "       ```",
        "     - **MANDATORY VERIFICATION (DEBUG PRINTS - DO NOT SKIP)**:",
        "       ```python",
        "       # Verify class order alignment BEFORE saving",
        "       print(f'DEBUG: First 3 LabelEncoder classes: {le.classes_[:3].tolist()}')",
        "       print(f'DEBUG: First 3 declared target cols: {submission_cols[:3]}')",
        "       print(f'DEBUG: Reorder indices (first 5): {reorder_idx[:5]}')",
        "       print(f'DEBUG: OOF shape after reorder: {oof_preds_aligned.shape}')",
        "       assert oof_preds_aligned.shape[1] == len(class_order), \\",
        "           f'Class count mismatch: {oof_preds_aligned.shape[1]} vs {len(class_order)}'",
        "       ```",
        "     - Hand this ordering to save_component_artifacts(class_order=class_order);",
        "       do not write the class_order file yourself.",
        "  4. During CV loop:",
        "     - Fill `oof_preds[val_idx]` with predictions for validation fold.",
        "     - Predict on test set and accumulate:",
        "       - Binary: `test_preds += model.predict_proba(X_test)[:, 1] / n_folds`",
        "       - Multi-class: `test_preds += model.predict_proba(X_test) / n_folds`",
        "       - Regression: `test_preds += model.predict(X_test) / n_folds`",
        "  4b. **OOF VALIDATION (MANDATORY BEFORE SAVE - RAISES ERROR IF INVALID)**:",
        "     ```python",
        "     # CRITICAL: Validate OOF BEFORE saving - broken OOF breaks ensemble",
        "     def validate_oof_before_save(oof_preds, test_preds, n_train, n_test):",
        "         # Check shapes",
        "         if oof_preds.shape[0] != n_train:",
        "             raise ValueError(f'OOF shape mismatch: {oof_preds.shape[0]} vs expected {n_train}')",
        "         if test_preds.shape[0] != n_test:",
        "             raise ValueError(f'Test shape mismatch: {test_preds.shape[0]} vs expected {n_test}')",
        "         ",
        "         # Validate only the canonical OOF-eligible rows. Temporal",
        "         # warm-up history has no honest OOF prediction and must stay NaN.",
        "         eligible_mask = CANONICAL_OOF_ELIGIBLE_MASK",
        "         eligible_oof = oof_preds[eligible_mask]",
        "         warmup_oof = oof_preds[~eligible_mask]",
        "         if np.any(~np.isfinite(eligible_oof)):",
        "             raise ValueError('OOF-eligible rows contain NaN or Inf')",
        "         if warmup_oof.size and not np.isnan(warmup_oof).all():",
        "             raise ValueError('Temporal warm-up OOF rows must remain NaN')",
        "         if np.isnan(test_preds).any():",
        "             nan_count = np.isnan(test_preds).sum()",
        "             raise ValueError(f'Test contains {nan_count} NaN values! Fix model training.')",
        "         ",
        "         # Check Inf",
        "         if np.isinf(test_preds).any():",
        "             raise ValueError('Test contains Inf values!')",
        "         ",
        "         # Report low-information predictions; let honest OOF selection decide usefulness",
        "         if eligible_oof.std() < 1e-10:",
        "             print('[VALIDATE] WARNING: OOF predictions have near-zero variance')",
        "         ",
        "         print(f'[VALIDATE] OOF passed: shape={oof_preds.shape}, eligible={eligible_mask.sum()}, var={eligible_oof.std():.4f}')",
        "         return True",
        "     ",
        "     # Validate before save_component_artifacts(...)",
        "     validate_oof_before_save(oof_preds_aligned, test_preds_aligned, n_train, n_test)",
        "     ```",
        "  5-7. Save every evidence artifact with ONE call to the injected helper.",
        "     This is the ONLY supported way to write them. Do not call np.save",
        "     for oof_/test_/train_ids_/test_ids_ yourself - hand-rolled saves are",
        "     what silently produce wrong filenames, unaligned rows and pickled",
        "     ID arrays that the validator then rejects:",
        "     ```python",
        "     save_component_artifacts(",
        "         oof_preds_aligned, test_preds_aligned,",
        "         test_ids=test_ids,           # omit to use CANONICAL_TEST_IDS",
        "         class_order=class_order,     # multiclass only; omit otherwise",
        "     )",
        "     ```",
        "     The helper writes all four files under the injected component name and",
        "     checks row alignment and test-ID uniqueness before writing anything.",
        "  7. TEST IDS - what to pass:",
        "     - Omit test_ids entirely when the test rows are the canonical ones:",
        "       the helper then uses CANONICAL_TEST_IDS, which names every public",
        "       test row exactly once and is always unique.",
        "     - Pass test_ids explicitly ONLY when your predictions are in a",
        "       different order or cover different entities than the canonical test",
        "       rows. Then pass one semantic test record ID per prediction row,",
        "       derived from the test entities you actually loaded.",
        "     - Never pass a repeated value (a date, a class placeholder, or for",
        "       long submissions the expanded/encoded submission row key):",
        "       duplicate test IDs fail validation and the component is discarded",
        "       no matter how good its score was.",
        "  7b. TRAIN IDS: omit train_ids to use CANONICAL_TRAIN_IDS. Your OOF rows",
        "     MUST already be in canonical order - use align_train_to_canonical(df)",
        "     when loading the training table, never df.set_index(ID_COL), because",
        "     ID_COL may name row positions that no CSV column contains.",
        "  8. Ensemble will ONLY run if BOTH oof_{name}.npy AND test_{name}.npy exist for at least 2 models.",
        "  9. This enables the Ensemble Agent to use Stacking/Blending later.",
        "  10. **MANDATORY VERIFICATION BLOCK (DO NOT REMOVE - ADD AT END OF SCRIPT)**:",
        "     ```python",
        "     # === VERIFICATION (CRITICAL - PREVENTS SILENT FAILURES) ===",
        "     from pathlib import Path",
        "     import numpy as np",
        "     ",
        f"     oof_path = Path('{working_dir}') / 'models' / 'oof_{component_name}.npy'",
        f"     test_path = Path('{working_dir}') / 'models' / 'test_{component_name}.npy'",
        f"     class_order_path = Path('{working_dir}') / 'models' / 'class_order_{component_name}.npy'",
        "     ",
        "     # 1. Check files exist",
        "     assert oof_path.exists(), f'CRITICAL ERROR: OOF file not saved at {oof_path}'",
        "     assert test_path.exists(), f'CRITICAL ERROR: Test file not saved at {test_path}'",
        "     print(f'[VERIFY] OOF file: {oof_path.name} exists')",
        "     print(f'[VERIFY] Test file: {test_path.name} exists')",
        "     ",
        "     # 2. Load and validate shapes",
        "     oof = np.load(oof_path)",
        "     test = np.load(test_path)",
        "     print(f'[VERIFY] OOF shape: {oof.shape}, Test shape: {test.shape}')",
        "     ",
        "     # 3. Validate probability range (classification)",
        "     eligible_oof = oof[CANONICAL_OOF_ELIGIBLE_MASK]",
        "     warmup_oof = oof[~CANONICAL_OOF_ELIGIBLE_MASK]",
        "     if eligible_oof.min() < 0 or eligible_oof.max() > 1:",
        "         print(f'[VERIFY] WARNING: eligible OOF has values outside [0,1]: min={eligible_oof.min():.4f}, max={eligible_oof.max():.4f}')",
        "     if test.min() < 0 or test.max() > 1:",
        "         print(f'[VERIFY] WARNING: Test has values outside [0,1]: min={test.min():.4f}, max={test.max():.4f}')",
        "     ",
        "     # 4. Check canonical coverage via the NaN OOF sentinel. Zero is a",
        "     # legitimate prediction and must never be treated as an empty row.",
        "     if np.any(~np.isfinite(eligible_oof)):",
        "         raise ValueError('Eligible OOF rows contain NaN/Inf or are unfilled')",
        "     if warmup_oof.size and not np.isnan(warmup_oof).all():",
        "         raise ValueError('Temporal warm-up OOF rows must remain NaN')",
        "     if np.any(~np.isfinite(test)):",
        "         raise ValueError('Test predictions contain NaN or Inf values')",
        "     ",
        "     # 5. Verify class order (mutually exclusive multiclass)",
        "     requires_class_order = (",
        "         IS_CLASSIFICATION and TARGET_TYPE == 'single'",
        "         and oof.ndim == 2 and oof.shape[1] > 1",
        "     )",
        "     if requires_class_order and not class_order_path.exists():",
        "         raise ValueError('Required multiclass class_order artifact is missing')",
        "     if class_order_path.exists():",
        "         class_order = np.load(class_order_path, allow_pickle=False).tolist()",
        "         print(f'[VERIFY] Class order: {class_order[:3]}... ({len(class_order)} classes)')",
        "     ",
        "     print('[VERIFY] All artifact checks completed')",
        "     # === END VERIFICATION ===",
        "     ```",
    ]
    instructions.extend(build_oof_hygiene_instructions(working_dir, component_name))
    return instructions


def build_multi_seed_instructions(working_dir: str, component_name: str) -> list[str]:
    """Build multi-seed training instructions for ensemble diversity."""
    return [
        "\n🎲 MULTI-SEED TRAINING (ENSEMBLE DIVERSITY):",
        "  - Train the SAME model architecture with DIFFERENT random seeds",
        "  - KEEP the injected canonical folds fixed - only change model randomness",
        "  - VALIDATE complete OOF before including in average",
        "    ```python",
        "    seeds = [42, 1337, 2024, 7, 123]",
        f"    canonical_dir = Path('{working_dir}') / 'canonical'",
        "    folds = np.load(canonical_dir / 'folds.npy')",
        "    canonical_train_ids = np.load(canonical_dir / 'train_ids.npy', allow_pickle=True)",
        "    valid_oof, valid_test = [], []",
        "",
        "    for seed in seeds:",
        "        try:",
        "            model = LGBMClassifier(random_state=seed, ...)  # Only change seed",
        "            oof, test = train_cv(model, folds)  # SAME folds",
        "",
        "            # VALIDATE: exact canonical shape and finite coverage.",
        "            if oof.shape[0] != len(canonical_train_ids):",
        "                raise ValueError('Seed OOF row count violates canonical contract')",
        "            eligible_oof = oof[CANONICAL_OOF_ELIGIBLE_MASK]",
        "            warmup_oof = oof[~CANONICAL_OOF_ELIGIBLE_MASK]",
        "            if not np.all(np.isfinite(eligible_oof)) or not np.all(np.isfinite(test)):",
        "                raise ValueError('Seed produced non-finite or incomplete predictions')",
        "            if warmup_oof.size and not np.isnan(warmup_oof).all():",
        "                raise ValueError('Seed fabricated temporal warm-up OOF coverage')",
        "",
        "            valid_oof.append(oof)",
        "            valid_test.append(test)",
        "            print(f'   ✅ Seed {seed}: complete OOF, included in average')",
        "        except (RuntimeError, ValueError, OSError) as e:",
        "            print(f'   ⚠️ Seed {seed} failed: {e}')",
        "            continue",
        "",
        "    if len(valid_oof) == 0:",
        "        raise ValueError('No seed produced valid OOF')",
        "",
        "    # Average only valid seeds",
        "    final_oof = np.mean(valid_oof, axis=0)",
        "    final_test = np.mean(valid_test, axis=0)",
        "    class_order = None",
        "    if (",
        "        IS_CLASSIFICATION and TARGET_TYPE == 'single'",
        "        and final_test.ndim == 2 and final_test.shape[1] > 1",
        "    ):",
        "        class_order = list(CANONICAL_METADATA.get('class_order') or [])",
        "        if len(class_order) != final_test.shape[1]:",
        "            raise ValueError('Canonical multiclass class_order is missing or misaligned')",
        "    save_component_artifacts(",
        "        final_oof, final_test, class_order=class_order",
        "    )",
        "    print(f'   Multi-seed: average of {len(valid_oof)}/{len(seeds)} seeds')",
        "    ```",
        "  - DO NOT create separate folds per seed (complexity + misalignment risk)",
    ]


def build_oof_hygiene_instructions(working_dir: str, component_name: str) -> list[str]:
    """Build OOF hygiene instructions for robust stacking."""
    return [
        "\nOOF HYGIENE (STACKING SAFETY):",
        "  - Initialize OOF with NaN and validate it BEFORE saving: exact canonical shape and finite values on `CANONICAL_OOF_ELIGIBLE_MASK`.",
        "  - Temporal warm-up rows (`~CANONICAL_OOF_ELIGIBLE_MASK`) MUST remain NaN and MUST never enter metric/ensemble fitting.",
        "  - Save fold assignments used for each row (enables leakage checks):",
        "    ```python",
        f"    canonical_dir = Path('{working_dir}') / 'canonical'",
        "    fold_assignment = np.load(canonical_dir / 'folds.npy')",
        "    canonical_train_ids = np.load(canonical_dir / 'train_ids.npy', allow_pickle=True)",
        "    if len(fold_assignment) != len(canonical_train_ids):",
        "        raise ValueError('Canonical fold/ID length mismatch')",
        f"    np.save(str(Path('{working_dir}') / 'models' / 'fold_assignment_{component_name}.npy'), fold_assignment)",
        "    ```",
        "  - Ensure train row order is consistent: use the same index/order for X, y, and OOF.",
        "  - Never drop, duplicate, or reorder canonical training rows inside a model component.",
    ]


def build_calibration_instructions() -> list[str]:
    """Build probability calibration instructions."""
    return [
        "\nPROBABILITY CALIBRATION (RECOMMENDED BEFORE ENSEMBLE):",
        "  - Calibrate OOF probabilities per model before blending.",
        "  - Prefer Platt scaling (logistic) as default; use isotonic if reliability curves are concave.",
        "  - Save both raw and calibrated OOF: oof_raw_{name}.npy and oof_cal_{name}.npy.",
        "  - Choose calibrated only if Brier/log_loss improves; otherwise keep raw.",
    ]
